name: bus_desktop
description: "Sistema de Monitoramento do Transporte Escolar - SEMEC Conceição do Araguaia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icones padrão do iOS
  cupertino_icons: ^1.0.8

  # [BANCO DE DADOS] Essencial para resolver o erro do seu log
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  sqflite_common_ffi_web: ^0.4.0

  # [LOCALIZAÇÃO] Para o monitoramento em tempo real
  geolocator: ^10.1.1

  # [CÂMERA] Para o Reconhecimento Facial
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Se você tiver imagens na pasta assets, descomente as linhas abaixo:
  # assets:
  #   - assets/images/logo_semec.png