name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      # Este comando abaixo corrige o erro, criando os arquivos web necessários
      - run: flutter create . --platforms web
      # No seu arquivo deploy.yml, altere para:
      - run: flutter build web --release --base-href "/Bus-Desktop/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web